##
## EPITECH PROJECT, 2023
## zappy
## File description:
## Makefile
##

# SRCDIR = src

# SRCDIRS = $(SRCDIR) $(SRCDIR)/core $(SRCDIR)/Interfaces
# SRC_ALL = $(foreach dir,$(SRCDIRS),$(wildcard $(dir)/*.cpp))
# SRC_OBJ = $(SRC_ALL:.cpp=.o)

# CPPFLAGS = -W -Wall -Wextra -Iinclude -Iinclude/core -Iinclude/Interfaces -lconfig++ -g -pthread -std=c++20

# CC = g++ -g

# NAME = zappy_ai

# all: $(NAME)

# $(NAME): $(SRC_OBJ)
# 	$(CC) -o $@ $^ $(CPPFLAGS)

# clean:
# 	rm -f $(SRC_OBJ)
# 	rm -f /tmp/pizzeria_*
# 	rm -f socket/kitchen_socket*


# fclean: clean
# 	rm -f $(NAME)


# re: fclean all

# .PHONY: all clean fclean re
